### ISSUE TITLE
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directorybug:

### ISSUE THREAD

**Issue by Jonasmpi** [windmill-labs/windmill#3401]
### Describe the bug

**Description:**

Encountering an OSError related to missing CUDA libraries (libcudart.so.12 and libnvJitLink.so.12) when running a Python script that imports PyTorch within the Windmill worker container environment. This issue prevents the script from executing due to unmet CUDA dependencies for PyTorch. A sub-library that i use is required from PyTorch, no gpu-training or Inference is planned with windmill.

**Environment:**

    Windmill Version: CE v1.289.0-22-g7ce046679
    Docker Version: (Docker version 24.0.7, build afdd53b
    Docker Compose Version:Docker Compose version v2.21.0
    Host OS and Version: Ubuntu 20.04
    PyTorch Version in Worker: 2.2.1
    No-GPU on Host-Machine

**Steps to Reproduce:**

1. Deploy Windmill services using the provided docker-compose.yml configuration.
2. Execute a Python script thatuses "import torch" and save Draft
3. Press "Test" Button 

**Expected Behavior:**
The Python script executes successfully, with PyTorch leveraging available CUDA resources for CPU/GPU-accelerated tasks.

**Actual Behavior:**
The Python script fails to execute, producing the following error message related to missing CUDA libraries:
```

OSError: libcudart.so.12: cannot open shared object file: No such file or directory
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directory
```

**Possible Causes:**

 

### To reproduce

1. Deploy Windmill services using the provided docker-compose.yml configuration.
2. Execute a Python script thatuses "import torch" and save Draft
3. Press "Test" Button 

**Actual Behavior:**
The Python script fails to execute, producing the following error message related to missing CUDA libraries:
```

OSError: libcudart.so.12: cannot open shared object file: No such file or directory
OSError: libnvJitLink.so.12: cannot open shared object file: No such file or directory
```

### Expected behavior

The Python script executes successfully, with PyTorch leveraging available CUDA resources for CPU/GPU-accelerated tasks.

### Application version

CE v1.289.0-22-g7ce046679

### Additional Context

**Possible Causes:**

The Windmill worker image (${WM_IMAGE}) might not include the necessary CUDA libraries for the version of PyTorch being used (2.2.1), or there could be a path/environment variable misconfiguration preventing access to these libraries.

**Comment by rubenfiszel** [comment]
We maintain a CUDA image for EE: https://github.com/windmill-labs/windmill/pkgs/container/windmill-ee-cuda

If not EE, you will have to build your own images, you can follow the same pattern as our CUDA image: https://github.com/windmill-labs/windmill/blob/main/docker/DockerfileCuda

**Comment by Jonasmpi** [comment]
Thanks for the fast response.
Just to make sure i understand the capabilites/restrictions of windmill:

- To use torch within Windmill (CE) i have to use bash+docker to create my own container that i supply with the existing code? Theres no way to use the python3 Editor or supply it with a special container?

OR

- Or do i have to build my own CE Image that has CUDA Included based on ghcr.io/windmill-labs/windmill:main ?

For testing i pulled the Nvidia Docker via code editor+bash and image that was running with no Issues, but i would be limited to get the logic inside the container etc with bash.

**Comment by rubenfiszel** [comment]
The latter:
> 
    Or do i have to build my own CE Image that has CUDA Included based on ghcr.io/windmill-labs/windmill:main ?

**Comment by Jonasmpi** [comment]
To keep back to this. Thank you @rubenfiszel for the support. I got it fixed by building my own container

- Your image wasn't working with Pytorch for me so i had to make some fixes.
- As soon as i have some time and if appreciated i will create a PR for that (if its wanted)
- Looking at the stack of Windmill, the strong focus on AI across the industry and the struggles with Frameworks (Python and CUDA) are you plan to launch the Scripts/Apps inside a Container?

**Comment by rubenfiszel** [comment]
Yes please, create a PR for it

For now we rather focus on worker groups and ability to easily set their init scripts but I agree the ability to define an image as context would be nice. It's harder than one would think because we wouldn't want to restrict ourselves to dind (docker-in-docker) but to apply to kubernetes pods and other infra that our docker template enable as well, and make it easy to add --gpus and custom options.

Does the image that you have setup not work as desired for that purpose ?

**Comment by Jonasmpi** [comment]
The image that i build is working for that setup right now.

The problem comes from the ecosystem that is required by most ML/DL Stacks. If i have a trained model from framework X version Y i need a different cuda setup. (e.g. [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/))
For new models i can always run with the newest stack that i train them on. If i want to use an old model e.g. pytorch 1.15 need to create a new image for that specific version. And this affects inferencing as well as training (thats not done on windmill right now)

A possible temporary workaround could be:
- That i build Docker-Images specific for the version (in my case cuda-toolkit-12-1)
- I register worker with that specific Dockerfile that are now used for those tasks

**Comment by aditio-eka** [comment]
Hi  @Jonasmpi @rubenfiszel, i am facing same problem, Could you share the step-by-step to fix it?
